# utils\configs\fusion_2.yaml

# 模型参数
bert_dim: 768
hidden_dim: 128
num_classes: 2
dropout: 0.5
fusion_type: attention
graph_dim: 5000

# 训练参数
epochs: 200
learning_rate: 0.0005
weight_decay: 0.0005
val_ratio: 0.2
test_ratio: 0.1
seed: 62

# 数据路径
dataset_path: dataset/cresci-rtbust-2019/cresci_cleaned.csv
bert_embedding_path: fusion_2/bert_embeddings.pt

# 图构建参数
k: 5

# 保存路径
save_path: fusion_2/checkpoints_seed62